vertx:
  mysql:
    client:
      port: 3306
      host: localhost
      database: local
      user: root
      password: ""
      maxSize: 5

datasource:
  table-name: local_customers

datasources:
  default:
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8:///db