#env: prod
#vertx:
#  mysql:
#    client:
#      port: 3306
#      host: sjlending.com
#      database: sjlending
#      user: sjlending
#      password: Sujji12!1
#      maxSize: 5
#
#datasource:
#  table-name: ${env}_customers

vertx:
  mysql:
    client:
      port: 3306
      host: localhost
      database: local
      user: root
      password: ""
      maxSize: 5

datasource:
  table-name: local_customers

datasources:
  default:
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8:///db